import { 
    TicketPercent,
    Boxes,
    Settings,
    User,
    LogOut,
    PanelLeft,
    PanelLeftIcon, 
    ChevronDown,
    SunMoon,
    AlertTriangle,
    OctagonX,
    Plus,
    Edit,
    SearchX,
    UploadCloud,
    X,
    Trash,
    Image as ImageIcon,
    Star,
    Trash2,
    Pencil,
    Check,
    Loader2,
    Eye,
    EyeOff,
    Lock,
    Mail,
    Camera,
    ChevronRight,
    Phone,
    FolderClosed,
    Grid2X2,
    Minus,
    TrendingUp,
    TrendingDown,
    Users,
    Package,
    ShoppingCart,
    DollarSign
} from "lucide-react";

import { 
    CategoriesIcon,
    CustomersIcon,
    DashboardIcon,
    DiscountsIcon,
    BrandAndAttributesIcon,
    OrdersIcon,
    ProductsIcon,
} from './custom/sidebar-icon'



export const LUCIDE_ICON_MAP = {
    TicketPercent,
    Boxes,
    Settings,
    User,
    LogOut,
    PanelLeft,
    PanelLeftIcon,
    ChevronDown,
    SunMoon,
    AlertTriangle,
    OctagonX,
    Plus,
    Edit,
    SearchX,
    UploadCloud,
    X,
    Trash,
    ImageIcon,
    Star,
    Trash2,
    Pencil,
    Check,
    Loader2,
    Eye,
    EyeOff,
    Lock,
    Mail,
    Camera,
    ChevronRight,
    Phone,
    FolderClosed,
    Grid2X2,
    Minus,
    TrendingUp,
    TrendingDown,
    Users,
    Package,
    ShoppingCart,
    DollarSign
}

export const CUSTOM_ICON_MAP = {
    dashboard: DashboardIcon,
    orders: OrdersIcon,
    products: ProductsIcon,
    customers: CustomersIcon,
    categories: CategoriesIcon,
    "brand-and-attributes": BrandAndAttributesIcon,
    discounts: DiscountsIcon
}
